name: dlt-april-cal
channels:
  - conda-forge
dependencies:
  - python=3.8.10
  - notebook=6.1.4
  - matplotlib=3.3.1
  - pandas=1.1.3
  - scipy=1.5.0
  - imageio=2.9.0
  - pip=20.2.3
  - pyyaml=5.3.1
  - pip:
      - pymvg==2.0.0
