name: test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15, macos-11]

    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: false

      - name: Create and test newly created conda environment
        shell: bash -l {0}
        run: |
          conda env create --name TEST --file environment.yml
          source activate TEST
          jupyter nbconvert --to notebook --execute tutorial.ipynb
